# Generated by Django 5.2.4 on 2025-08-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodtest',
            name='hemoglobin',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='platelet_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='rbc_count',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='sugar_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='uric_acid_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bloodtest',
            name='wbc_count',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
