# Generated by Django 5.2.4 on 2025-09-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospitaluser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
