# Generated by Django 5.2.4 on 2025-08-23 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_managers_alter_user_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='core.hospital'),
        ),
    ]
