# Generated by Django 5.2.6 on 2025-09-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_bloodtest_prediction_fields'),
    ]

    operations = [
    migrations.AddField(
        model_name='hospitaluser',
        name='email',
        field=models.EmailField(max_length=254, unique=True, null=True, blank=True),
    ),
    ]

